# Generated by Django 5.2.17 on 2026-08-15 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=100)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('tool_call_count', models.PositiveIntegerField(default=0)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-imported_at', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_message_id', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=255)),
                ('tool_call_id', models.CharField(blank=True, max_length=255)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='history.historysession')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('imported_sessions', models.PositiveIntegerField(default=0)),
                ('skipped_sessions', models.PositiveIntegerField(default=0)),
                ('imported_messages', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_import_batches', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='historysession',
            index=models.Index(fields=['owner', 'started_at'], name='history_owner_started_idx'),
        ),
        migrations.AddIndex(
            model_name='historysession',
            index=models.Index(fields=['owner', 'title'], name='history_owner_title_idx'),
        ),
        migrations.AddConstraint(
            model_name='historysession',
            constraint=models.UniqueConstraint(fields=('owner', 'external_id'), name='unique_history_session_per_owner'),
        ),
        migrations.AddIndex(
            model_name='historymessage',
            index=models.Index(fields=['session', 'timestamp'], name='message_session_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='historymessage',
            constraint=models.UniqueConstraint(condition=models.Q(('source_message_id', ''), _negated=True), fields=('session', 'source_message_id'), name='unique_source_message_per_session'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['owner', 'created_at'], name='import_owner_created_idx'),
        ),
    ]
