# Generated by Django 5.2.17 on 2026-08-17 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_session_relationships(apps, schema_editor):
    HistorySession = apps.get_model("history", "HistorySession")
    ImportBatch = apps.get_model("history", "ImportBatch")

    sessions = list(HistorySession.objects.all())
    uploader_by_owner = {}
    for owner_id in {session.owner_id for session in sessions}:
        uploader_ids = set(
            ImportBatch.objects.filter(
                owner_id=owner_id,
                status="succeeded",
                imported_sessions__gt=0,
            ).values_list("uploader_id", flat=True)
        )
        if len(uploader_ids) != 1:
            raise RuntimeError(
                f"History owner {owner_id} must have exactly one successful uploader"
            )
        uploader_by_owner[owner_id] = uploader_ids.pop()

    for session in sessions:
        session.uploader_id = uploader_by_owner[session.owner_id]
        session.save(update_fields=["uploader"])

    session_ids = {(session.owner_id, session.external_id): session.pk for session in sessions}
    candidate_parents = {}
    for session in sessions:
        raw_parent = (session.raw_metadata or {}).get("parent_session_id")
        if raw_parent in (None, ""):
            continue
        if not isinstance(raw_parent, str):
            raise RuntimeError(f"History session {session.pk} has an invalid parent_session_id")
        parent_external_id = raw_parent.strip()
        if not parent_external_id or len(parent_external_id) > 255:
            raise RuntimeError(f"History session {session.pk} has an invalid parent_session_id")
        parent_pk = session_ids.get((session.owner_id, parent_external_id))
        if parent_pk is None:
            raise RuntimeError(f"History session {session.pk} has a missing parent")
        if parent_pk == session.pk:
            raise RuntimeError(f"History session {session.pk} has a parent cycle")
        candidate_parents[session.pk] = parent_pk

    for child_pk, parent_pk in candidate_parents.items():
        seen = {child_pk}
        ancestor_pk = parent_pk
        depth = 1
        while ancestor_pk in candidate_parents:
            if ancestor_pk in seen:
                raise RuntimeError(f"History session {child_pk} has a parent cycle")
            seen.add(ancestor_pk)
            ancestor_pk = candidate_parents[ancestor_pk]
            depth += 1
        if ancestor_pk in seen:
            raise RuntimeError(f"History session {child_pk} has a parent cycle")
        if depth > 1:
            raise RuntimeError(f"History session {child_pk} exceeds one subagent level")

    for child_pk, parent_pk in candidate_parents.items():
        HistorySession.objects.filter(pk=child_pk).update(parent_session_id=parent_pk)


def clear_session_relationships(apps, schema_editor):
    HistorySession = apps.get_model("history", "HistorySession")
    HistorySession.objects.update(parent_session_id=None, uploader_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historysession",
            name="parent_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subagent_threads",
                to="history.historysession",
            ),
        ),
        migrations.AddField(
            model_name="historysession",
            name="uploader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_history_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            backfill_session_relationships,
            clear_session_relationships,
        ),
        migrations.AlterField(
            model_name="historysession",
            name="uploader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_history_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
