# Generated by Django 5.2.17 on 2026-08-18 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_add_session_relationships_and_uploader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemoryPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_markdown', models.TextField(blank=True)),
                ('user_markdown', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_pool', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner_id'],
            },
        ),
    ]
