# Generated by Django 5.2.17 on 2026-08-25 07:42

from django.db import migrations, models
from django.utils.crypto import salted_hmac

# Matches AbstractBaseUser.get_session_auth_hash so live sessions bound here
# stay valid until the user's password actually changes.
SESSION_AUTH_KEY_SALT = (
    "django.contrib.auth.models.AbstractBaseUser.get_session_auth_hash"
)


def backfill_auth_state_digest(apps, schema_editor):
    ClientSession = apps.get_model("history", "ClientSession")
    for session in ClientSession.objects.select_related("account__user").iterator():
        session.auth_state_digest = salted_hmac(
            SESSION_AUTH_KEY_SALT,
            session.account.user.password,
            algorithm="sha256",
        ).hexdigest()
        session.save(update_fields=["auth_state_digest"])


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0007_trace_token_client_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsession",
            name="auth_state_digest",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="clientsession",
            name="revocation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("signed_out", "Signed out"),
                    ("session_revoked", "Session revoked"),
                    ("superseded", "Superseded by reissue"),
                    ("credential_changed", "Credential changed"),
                    ("account_disabled", "Account disabled"),
                    ("account_revoked", "Account revoked"),
                ],
                max_length=32,
            ),
        ),
        # Reverse is a deliberate no-op: keep retained evidence intact.
        migrations.RunPython(
            backfill_auth_state_digest, migrations.RunPython.noop
        ),
    ]
